name: Lint Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and Lint Backend
        run: |
          cd backend
          npm install
          npx eslint .

      - name: Install and Lint Frontend
        run: |
          cd frontend
          npm install
          npx eslint .
